# Unique name for this workflow
name: Push to development branch.

# Definition when the workflow should run
on:
    push:
      branches: [ development ]
      paths:
        - 'force-app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event_name == 'push'
    - uses: actions/setup-node@v1
      with:
        node-version: '>=14'
        check-latest: true
   
    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
            
    - name: 'Populate auth file with SFDX_URL secret'
      shell: bash
      run: 'echo ${{ secrets.SFDX_URL}} > SFDX_QA'
      
    - name: 'Authenticate against dev hub'
      run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_QA -s -a LRQA
      
    - name: 'Run checkonly deploy'
      run: sfdx force:source:deploy -p force-app --testlevel RunLocalTests --json --checkonly
